### ISSUE TITLE
GoogleMobileAdsSettings missing (mono script)

### ISSUE THREAD

**Issue by Hamed1984** [tapsellorg/TapsellPlusSDK-UnitySample2020#1]
salam
script GoogleMobileAdsSettings miss shode?

**Comment by behrooz-fard** [comment]
Hi Dear Hamed,
GoogleMobileAdsSettings exists in our [unity packages](https://github.com/tapsellorg/TapsellPlusSDK-UnitySample2020/releases).

**Comment by Hamed1984** [comment]
من نگفتم فایلش نیست
منظورم اینه که وقتی فایل GoogleMobileAdsSettings
انتخاب می کنی تو قسمت اینسپکتور نشون میده که یک اسکریپت باید باشه که میس شده
missing (mono script)

**Comment by behrooz-fard** [comment]
چون تنظیمات ادموب داخل یونیتی انجام نمی‌شود نیازی به کامل بودن آن نیست. صرفا مواردی که برای نمایش تبلیغ همسان به آن‌ها احتیاج بوده در یونیتی پکیج قرار گرفته است.
